'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const F=require('../driveup-fuel.js'),C=require('../overview-income-chart.js');
module.exports=async function(){
 let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS fuel/overview:',name);};
 const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
 const ref=(date,odometer,liters,fullTank=false)=>({date,odometer,liters,fullTank,price:6,total:liters*6,fuelType:'Gasolina'});
 const state=(refuels,currentOdometer)=>({settings:{currentOdometer,tankCapacity:15,confirmedConsumption:27,fuelPrice:6,preferences:{}},refuels,sessions:[]});
 // Synthetic regression fixture: a slightly exhausted estimate used to block later fills.
 const fixture=()=>state([ref('2026-01-01',1000,13.5,true),ref('2026-01-08',1405.4,10),ref('2026-01-11',1669.4,4.55),ref('2026-01-16',1779.4,10),ref('2026-01-18',2069.4,3.578)],2109.4);
 test('regression reproduces original block and proves restart after refill',()=>{
  const source=fs.readFileSync(require.resolve('../driveup-fuel.js'),'utf8');
  const old=source.replace(/      \/\/ A modelled depletion[\s\S]*?(?=      liters = Math\.max)/,"      if (liters < -0.01) { out.reason='Insufficient estimated fuel'; return out; }\n");
  assert.notEqual(source,old);const context=vm.createContext({module:{exports:{}}});vm.runInContext(old,context);
  assert.equal(context.module.exports.estimate(fixture()).known,false);
  const m=F.estimate(fixture());assert.equal(m.known,true);near(m.range,56.606);near(m.liters,2.0965185185185184);
 });
 test('later refill updates range despite a depleted previous estimate',()=>{
  const s=state([ref('2026-01-01',1000,10,true)],1500);assert.equal(F.estimate(s).range,0);
  s.refuels.push(ref('2026-01-02',1500,5));near(F.estimate(s).range,135);
 });
 test('residual positive fuel is retained on partial refill',()=>near(F.estimate(state([ref('2026-01-01',1000,10,true),ref('2026-01-02',1081,2)],1081)).liters,14));
 test('backdated entries are ordered by event rather than insertion',()=>{const s=fixture();s.refuels.reverse();near(F.estimate(s).range,56.606);});
 test('missing initial tank reference remains unknown not a false zero',()=>{const m=F.estimate(state([ref('2026-01-02',1500,5)],1500));assert.equal(m.known,false);assert.equal(m.range,null);});
 test('restart is disclosed instead of claiming measured fuel',()=>{const m=F.estimate(fixture());assert.equal(m.balanceAdjusted,true);assert.match(m.warning,/saldo anterior zero/);assert.equal(m.consumption.kind,'estimated');});
 test('normal uninterrupted estimate has no adjustment warning',()=>{const m=F.estimate(state([ref('2026-01-01',1000,10,true)],1100));assert.equal(m.balanceAdjusted,false);assert.equal(m.warning,'');});
 test('manual odometer decreases only the estimated remaining range',()=>{const s=fixture(),range=F.estimate(s).range;s.settings.currentOdometer+=10;near(F.estimate(s).range,range-10);});
 test('saving editing and removing session kilometers never consumes tank fuel',()=>{const s=fixture(),before=F.estimate(s).range;s.sessions.push({km:100,tripKm:60});near(F.estimate(s).range,before);s.sessions[0].km=200;near(F.estimate(s).range,before);s.sessions=[];near(F.estimate(s).range,before);near(s.settings.currentOdometer,2109.4);});
 test('calculations do not mutate any saved records or configured consumption',()=>{const s=fixture(),before=JSON.stringify(s);F.estimate(s);assert.equal(JSON.stringify(s),before);});
 test('historical price and consumption snapshots remain unchanged',()=>{const s=fixture(),old={fuelPrice:5,fuelConsumption:30};assert.deepEqual(F.snapshot(s,'2026-01-18',old),old);});
 test('a fresh full tank restores the reference without adjustment warning',()=>{const s=fixture();s.refuels.push(ref('2026-01-20',2200,8,true));s.settings.currentOdometer=2200;const m=F.estimate(s);assert.equal(m.known,true);assert.equal(m.balanceAdjusted,false);near(m.liters,15);});
 test('exhausted current estimate still shows zero and warns',()=>{const s=fixture();s.settings.currentOdometer=2500;const m=F.estimate(s);assert.equal(m.range,0);assert.match(m.warning,/esgotada/);});
 test('invalid decreasing odometer remains blocked',()=>{const s=fixture();s.refuels[2].odometer=1300;assert.equal(F.estimate(s).known,false);});
 test('current odometer below last refill prompts manual correction',()=>{const s=fixture();s.settings.currentOdometer=1500;const m=F.estimate(s);assert.equal(m.known,false);assert.match(m.reason,/manualmente/);});
 test('over-capacity data is not silently accepted',()=>assert.equal(F.estimate(state([ref('2026-01-01',1000,10,true),ref('2026-01-02',1000,3)],1000)).known,false));
 test('future refills are excluded from current estimate',()=>{const s=fixture();s.refuels.push(ref('2026-12-01',2500,10,true));near(F.estimate(s,'2026-02-01').range,56.606);});
 test('no configured consumption still requests a measurement',()=>{const s=fixture();s.settings.confirmedConsumption=0;assert.equal(F.estimate(s).known,false);});
 const data=[{date:'2026-01-01',gross:110,net:80},{date:'2026-01-02',gross:210,net:160}];
 test('default view remains net',()=>{assert.equal(C.model(data).key,'net');near(C.model(data).average,120);});
 test('gross view uses saved gross without counting tips twice',()=>{const m=C.model(data.map(d=>({...d,tip:10})),'gross');assert.deepEqual(m.points.map(x=>x.value),[110,210]);near(m.average,160);near(m.sum,320);});
 test('filter does not change original financial rows',()=>{const before=JSON.stringify(data);C.model(data,'gross');C.model(data,'net');assert.equal(JSON.stringify(data),before);});
 test('each view changes titles legend and scale',()=>{const a=C.model(data,'net'),b=C.model(data,'gross');assert.notEqual(a.title,b.title);assert.notEqual(a.label,b.label);assert.notEqual(a.upper,b.upper);});
 test('empty month displays an empty state not stale earnings',()=>{const m=C.model([],'gross');assert.equal(m.average,0);assert.match(C.svgContent(m,String,String),/Nenhuma sessão/);});
 test('negative net has a visible negative axis',()=>{const m=C.model([{date:'2026-01-01',gross:10,net:-10}]);assert.ok(m.lower<-10);assert.equal(m.upper,0);near(m.average,-10);});
 test('zero totals never produce invalid coordinates',()=>assert.doesNotMatch(C.svgContent(C.model([{date:'2026-01-01',gross:0,net:0}]),String,String),/NaN|Infinity/));
 test('single day has a valid centered coordinate',()=>{const svg=C.svgContent(C.model(data.slice(0,1),'gross'),String,String);assert.match(svg,/cx="443"/);});
 test('unknown metric defaults safely to net',()=>assert.equal(C.model(data,'invalid').key,'net'));
 test('gross tooltips and average use gross values',()=>{const svg=C.svgContent(C.model(data,'gross'),v=>'R$ '+v,d=>d);assert.match(svg,/data-chart-average="160"/);assert.match(svg,/R\$ 210/);assert.match(svg,/data-income-series="gross"/);});
 test('date and tooltip content are escaped',()=>{const svg=C.svgContent(C.model([{date:'<script>alert(1)</script>',gross:50}],'gross'),String,String);assert.ok(!svg.includes('<script>'));});
 test('nonfinite values cannot break SVG rendering',()=>assert.doesNotMatch(C.svgContent(C.model([{date:'a',net:NaN},{date:'b',net:Infinity}]),String,String),/NaN|Infinity/));
 // Exercise the real renderer's dropdown handler with a small isolated DOM.
 let owner='A';const cache=new Map();
 const storage={getItem:k=>cache.get(k)||null,setItem:(k,v)=>cache.set(k,v)};
 const el=()=>({textContent:'',innerHTML:'',value:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;}});
 let selector=el(),title=el(),subtitle=el(),legend=el(),svg=el();
 const panel={querySelector:q=>({'.overview-chart-range':selector,'h2':title,'.overview-chart-heading .sub':subtitle,'.overview-chart-legend':legend}[q])};svg.closest=()=>panel;
 const doc={getElementById:id=>id==='overviewChart'?svg:null};
 const options={document:doc,getOwner:()=>owner,getStorage:()=>storage,money:v=>'R$ '+v,date:d=>d};
 let draw=C.createRenderer(options);draw(data);
 test('renderer exposes both requested filter choices',()=>{assert.match(selector.innerHTML,/Ganhos líquidos/);assert.match(selector.innerHTML,/Ganhos brutos/);assert.equal(selector.value,'net');});
 selector.value='gross';selector.onchange();
 test('selecting gross immediately updates chart title average and tooltips',()=>{assert.match(title.textContent,/brutos/);assert.match(legend.innerHTML,/160/);assert.equal(svg.attrs['data-income-metric'],'gross');});
 test('redrawing after month switch preserves filter but uses new month',()=>{draw([{date:'2026-02-01',gross:50,net:25}]);assert.equal(selector.value,'gross');assert.match(legend.innerHTML,/50/);assert.doesNotMatch(svg.innerHTML,/data-chart-average="160"/);});
 test('reloading renderer retains the choice for the same account',()=>{draw=C.createRenderer(options);draw(data);assert.equal(selector.value,'gross');});
 test('a different account starts with its own default',()=>{owner='B';draw(data);assert.equal(selector.value,'net');});
 test('switching back restores previous account choice',()=>{owner='A';draw(data);assert.equal(selector.value,'gross');});
 test('blocked browser storage does not prevent filter use',()=>{const d=C.createRenderer({...options,getStorage:()=>{throw Error('blocked');}});d(data);selector.value='gross';selector.onchange();assert.equal(selector.value,'gross');});
 test('stale account handler cannot change the new account',()=>{owner='A';draw(data);const old=selector.onchange;owner='C';selector.value='gross';old();draw(data);assert.equal(selector.value,'net');});
 console.log(`Fuel/overview regression tests: ${count} passed. No live writes.`);return count;
};
if(require.main===module)module.exports().catch(e=>{console.error(e);process.exitCode=1;});
